# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Second_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frond_End_GUI(object):
    def setupUi(self, Frond_End_GUI):
        Frond_End_GUI.setObjectName("Frond_End_GUI")
        Frond_End_GUI.resize(950, 655)
        self.centralwidget = QtWidgets.QWidget(Frond_End_GUI)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, -80, 871, 731))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resources/TIM.gif"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 505, 631, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 490, 81, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"font: 75 11pt \"Tw Cen MT\";\n"
"color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 490, 75, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"font: 75 11pt \"Tw Cen MT\";\n"
"color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        Frond_End_GUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(Frond_End_GUI)
        QtCore.QMetaObject.connectSlotsByName(Frond_End_GUI)

    def retranslateUi(self, Frond_End_GUI):
        _translate = QtCore.QCoreApplication.translate
        Frond_End_GUI.setWindowTitle(_translate("Frond_End_GUI", "MainWindow"))
        self.label_2.setText(_translate("Frond_End_GUI", "TextLabel"))
        self.pushButton.setText(_translate("Frond_End_GUI", "Start"))
        self.pushButton_2.setText(_translate("Frond_End_GUI", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frond_End_GUI = QtWidgets.QMainWindow()
    ui = Ui_Frond_End_GUI()
    ui.setupUi(Frond_End_GUI)
    Frond_End_GUI.show()
    sys.exit(app.exec_())
